# Table 1: Inception without BatchNorm with weight decay, no crop augmentation

# Experiment identification
experiment_id: inception_wo_bn_cifar10_wd0.00005_lr_0.005

# Model configuration
model:
  model_name: inception_no_bn
  num_classes: 10

# Data configuration
data:
  dataset: cifar10
  data_root: ./data
  crop_size: 28
  random_crop: false  # Center crop (baseline)
  augment_flip_rotate: false
  batch_size: 128
  num_workers: 4
  pin_memory: true

# Training hyperparameters
training:
  num_epochs: 100
  learning_rate: 0.005
  momentum: 0.9
  lr_schedule: exponential
  optimizer: sgd

# Regularization
regularization:
  weight_decay: 0.0005

# Early stopping
early_stopping:
  early_stopping_enabled: true
  early_stopping_window: 6
  early_stopping_min_epochs: 40

# Logging and checkpointing
logging:
  use_wandb: true
  wandb_project: FOLI-Project
  wandb_entity: alirezasakhaeirad
  save_dir: ./checkpoints/table1
  log_interval: 10

# Device
device: cuda

# Reproducibility
seed: 42
