# Table 1: MLP-3x512 with random labels
# This is the baseline configuration with no explicit regularization

# Experiment identification
experiment_id: mlp3_cifar10_random_labels

# Model configuration
model:
  model_name: mlp_3x512
  num_classes: 10

# Data configuration
data:
  dataset: cifar10
  data_root: ./data
  crop_size: 28
  random_crop: false  # Center crop (baseline)
  augment_flip_rotate: false
  batch_size: 128
  num_workers: 4
  pin_memory: true
  randomization: random_labels

# Training hyperparameters
training:
  num_epochs: 100
  learning_rate: 0.01
  momentum: 0.9
  lr_schedule: exponential
  optimizer: sgd

# Regularization
regularization:
  weight_decay: 0.0

# Early stopping
early_stopping:
  early_stopping_enabled: false
  early_stopping_window: 10
  early_stopping_min_epochs: 25

# Logging and checkpointing
logging:
  use_wandb: true
  wandb_project: FOLI-Project
  wandb_entity: alirezasakhaeirad
  save_dir: ./checkpoints/table1
  log_interval: 10

# Device
device: cuda

# Reproducibility
seed: 42
