dataset: cifar10
num_epochs: 100
batch_size: 128
optimizer: sgd
momentum: 0.9
augment_flip_rotate: false
center_crop_size: 28
device: cuda
use_wandb: true
wandb_project: FOLI-Project
wandb_entity: alirezasakhaeirad
save_dir: ./checkpoints/table1
model_name: mlp_3x512
learning_rate: 0.01
lr_schedule: step
randomization: random_labels
weight_decay: 0.0
random_crop: false
