# ImageNet: Inception with random labels
# This configuration uses 50% of the ImageNet training data with random labels

# Experiment identification
experiment_id: inception_imagenet_random_labels_50pct

# Model configuration
model:
  model_name: inception
  num_classes: 1000
  input_shape: [3, 224, 224]

# Data configuration
data:
  dataset: imagenet
  data_root: ./data/imagenet
  crop_size: 224
  random_crop: false  # Center crop (baseline)
  augment_flip_rotate: false
  batch_size: 128
  num_workers: 4
  pin_memory: true
  randomization: random_labels
  data_fraction: 0.5  # Use 50% of the data

# Training hyperparameters
training:
  num_epochs: 100
  learning_rate: 0.1
  momentum: 0.9
  lr_schedule: exponential
  optimizer: sgd

# Regularization
regularization:
  weight_decay: 0.0

# Early stopping
early_stopping:
  early_stopping_enabled: false
  early_stopping_window: 6
  early_stopping_min_epochs: 25

# Logging and checkpointing
logging:
  use_wandb: true
  wandb_project: FOLI-Project
  wandb_entity: alirezasakhaeirad
  save_dir: ./checkpoints/imagenet
  log_interval: 10

# Device
device: cuda

# Reproducibility
seed: 42
