# Baseline MLP 1x512 on CIFAR10 with true labels
# Corresponds to "MLP 1x512" row in Table 1 (no explicit regularization)

model_name: mlp_1x512
dataset: cifar10
data_root: ./data

# No randomization - use true labels
randomization: null
corruption_prob: 0.0
randomization_seed: 42

# No explicit regularization
weight_decay: 0.0
random_crop: false
augment_flip_rotate: false

# Training hyperparameters
batch_size: 128
num_epochs: 100
learning_rate: 0.01
momentum: 0.9
optimizer: sgd
lr_schedule: null

# Preprocessing
center_crop_size: 28

# Logging
use_wandb: false
wandb_project: FOLI-Project
wandb_entity: alirezasakhaeirad
save_dir: ./checkpoints
log_interval: 10

# Reproducibility
seed: 42
device: cuda

