# Inception with Weight Decay on CIFAR10
# Tests effect of L2 regularization on true labels

model_name: small_inception
dataset: cifar10
data_root: ./data

# No randomization - use true labels
randomization: null
corruption_prob: 0.0
randomization_seed: 42

# Enable weight decay only
weight_decay: 0.0005
random_crop: false
augment_flip_rotate: false

# Training hyperparameters
batch_size: 2048
num_epochs: 100
learning_rate: 0.04
momentum: 0.9
optimizer: sgd
lr_schedule: null

# Preprocessing
center_crop_size: 28

# Logging
use_wandb: false
wandb_project: FOLI-Project
wandb_entity: alirezasakhaeirad
save_dir: ./checkpoints
log_interval: 10

# Reproducibility
seed: 42
device: cuda

