# Shuffled Pixels experiment with Inception on CIFAR10
# Shuffle pixels within each image while keeping labels
# Tests if spatial structure matters

model_name: small_inception
dataset: cifar10
data_root: ./data

# Shuffle pixels within images
randomization: shuffled_pixels
corruption_prob: 0.0
randomization_seed: 42

# No explicit regularization
weight_decay: 0.0
random_crop: false
augment_flip_rotate: false

# Training hyperparameters
batch_size: 1024
num_epochs: 100
learning_rate: 0.028
momentum: 0.9
optimizer: sgd
lr_schedule: null

# Preprocessing
center_crop_size: 28

# Logging
use_wandb: false
wandb_project: FOLI-Project
wandb_entity: alirezasakhaeirad
save_dir: ./checkpoints
log_interval: 10

# Reproducibility
seed: 42
device: cuda

