# CIFAR-100: Inception with normal labels
# This configuration uses 100% of the CIFAR-100 training data

# Experiment identification
experiment_id: inception_cifar100_normal

# Model configuration
model:
  model_name: inception
  num_classes: 100

# Data configuration
data:
  dataset: cifar100
  data_root: ./data
  crop_size: 28
  random_crop: false  # Center crop (baseline)
  augment_flip_rotate: false
  batch_size: 128
  num_workers: 4
  pin_memory: true
  randomization: none
  data_fraction: 1.0  # Use 100% of the data

# Training hyperparameters
training:
  num_epochs: 100
  learning_rate: 0.1
  momentum: 0.9
  lr_schedule: exponential
  optimizer: sgd

# Regularization
regularization:
  weight_decay: 0.0

# Early stopping
early_stopping:
  early_stopping_enabled: false
  early_stopping_min_epochs: 25
  early_stopping_window: 6

# Logging and checkpointing
logging:
  use_wandb: true
  wandb_project: FOLI-Project
  wandb_entity: alirezasakhaeirad
  save_dir: ./checkpoints/cifar100
  log_interval: 10

# Device
device: cuda

# Reproducibility
seed: 42
