# Random Labels with Full Augmentation - Appendix E, Table 4
# Tests if flip+rotate augmentation prevents fitting random labels
# Finding: Inception achieves 99.28% training accuracy

model_name: inception
dataset: cifar10
data_root: ./data

# Complete label randomization
randomization: random_labels
corruption_prob: 0.0
randomization_seed: 42

# Enable full augmentation on random labels
weight_decay: 0.0
random_crop: false
augment_flip_rotate: true

# Training hyperparameters
batch_size: 1024
num_epochs: 150  # May need more epochs with augmentation
learning_rate: 0.028
momentum: 0.9
optimizer: sgd
lr_schedule: null

# Preprocessing
center_crop_size: 28

# Logging
use_wandb: false
wandb_project: FOLI-Project
wandb_entity: alirezasakhaeirad
save_dir: ./checkpoints
log_interval: 10

# Reproducibility
seed: 42
device: cuda

