# Random Labels with Weight Decay - MLP 1x512 - Appendix E, Table 4
# Finding: MLP 1x512 achieves 99.21% training accuracy with weight decay

model_name: mlp_1x512
dataset: cifar10
data_root: ./data

# Complete label randomization
randomization: random_labels
corruption_prob: 0.0
randomization_seed: 42

# Enable weight decay on random labels
weight_decay: 0.0001
random_crop: false
augment_flip_rotate: false

# Training hyperparameters
batch_size: 8192
num_epochs: 100
learning_rate: 0.16
momentum: 0.9
optimizer: sgd
lr_schedule: null

# Preprocessing
center_crop_size: 28

# Logging
use_wandb: false
wandb_project: FOLI-Project
wandb_entity: alirezasakhaeirad
save_dir: ./checkpoints
log_interval: 10

# Reproducibility
seed: 42
device: cuda

